config/routes.rb
WcccGaming::Application.routes.draw do
  devise_for :users
  resources :posts
  resources :pages, :only => [:edit, :update]
  resources :messages, :only => [:new, :create]
  get '/about' => 'pages#index', as: 'about'
  get '/news' => 'posts#news_list', as: 'news_list'
  get '/events' => 'posts#event_list', as: 'event_list'
  root 'posts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
        can :manage, :all
    else
        can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/message.rb
class Message
  include ActiveAttr::Model

  attribute :name
  attribute :email
  attribute :content

  validates_presence_of :name
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    admin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      ContactMailer.contact_email(@message).deliver
      redirect_to root_path, notice: "Message sent! Thank you for contacting us!"
    else
      render "new"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy, :create, :update, :new]
  load_and_authorize_resource
  def index
    @about_page = Page.first
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
  @page = Page.find(params[:id])
    if @page.update(page_params)
      redirect_to about_path
    else
      render 'edit'
    end
  end

  def show
  end

rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_url, :alert => exception.message
end


private
  def page_params
    params.require(:page).permit(:title, :content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy, :create, :update, :new]
  load_and_authorize_resource :except => [:news_list, :event_list]

def new
  @post = Post.new
end

def index
  @pagi = Post.paginate(:page => params[:page], :per_page => 3, :order => 'created_at desc')
  @events = Post.where("is_event = 'true'").reorder('event_date ASC').take(5)
end

def create
  @post = Post.new(post_params)
  if @post.save
    redirect_to @post
  else
    render 'new'
  end
end

def edit
  @post = Post.find(params[:id])
end

def update
  @post = Post.find(params[:id])

  if @post.update(post_params)
    redirect_to @post
  else
    render 'edit'
  end
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to posts_path
end

def show
  @post = Post.find(params[:id])
end

def news_list
  @posts = Post.paginate(:page => params[:page], :per_page => 7, :order => 'created_at desc')
end

def event_list
  @events = Post.where("is_event = 'true'").reorder('event_date desc').paginate(:page => params[:page], :per_page => 7)
end

rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_url, :alert => exception.message
end

private
  def post_params
    params.require(:post).permit(:title, :text, :summary, :is_event, :event_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    RedCloth.new(text).to_html.html_safe
  end

  def admin?
    current_user.admin
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_devise_errors.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/application/_events.html.erb
<h2><%= link_to "Upcoming Events", event_list_path %></h2>
<hr />
<% @events.each do |event| %>
  <% if event.event_date >= Time.zone.now - 1.day%>
  <div class="event">
      <div class="eventdate pull-left">
      <p><%= event.event_date.strftime("%d") %></p>
      <p><%= event.event_date.strftime("%b") %></p>
    </div>
    <div class="eventtitle pull-left">
      <h3><strong><%= link_to event.title, post_path(event) %></strong></h3>
    </div>
  </div>
  <% end %>
<% end %>

app/views/application/_posts.html.erb
<% @pagi.each do |post| %>
 <div class="panel panel-default">
  <div class="newsTitle panel-heading">
    <h3 class="pull-left">
      <strong><%= link_to post.title, post %></strong>
    </h3>
     <span class="pull-right"><%= post.created_at.strftime("%d %b. %Y") %></span>
  </div>
  <div class="panel-body">
    <p><%= markdown post.summary %></p>
    <%= link_to 'Read More', post, class: "btn btn-default" %>
    <% if user_signed_in? && admin? %>
    <div class="pull-right">
       <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
      <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-default" %>
    </div>
  <% end %>
  </div>
</div>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WCCC Gaming</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<div class="row">
  <div class="col-xs-12">
      <% if user_signed_in?%>
    <nav class="navbar navbar-default" role="navigation">
      <%= link_to "WCCC Gaming Account", root_path, :class => 'navbar-brand' %>
      <p class="navbar-text">Logged in as <strong><%= current_user.email %></strong>.</p>
      <ul class="nav navbar-nav">
      <% if admin? %>
          <li><%= link_to "New Post", new_post_path, :class => 'navbar-link' %></li>
      <% end %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      </ul>
    </nav>
  <% end %>
  </div>
</div>
<div class="row">
  <div class="col-xs-6 head">
    <h1 class="logo"><strong><%= link_to "WCCC Gaming", root_path %></strong></h1>
  </div>
  <div class="col-xs-6 head">
    <ul id="nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></a></li>
      <li><%= link_to "News", news_list_path %></li>
      <li><%= link_to "Events", event_list_path %></li>
    </ul>
  </div>
</div>
  <%= render 'devise_errors' %>
  <%= yield %>
</div>
</body>
</html>

app/views/messages/new.html.erb
<h2 class="text-center"><strong>Contact Us</strong></h2>
<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div>
        <% @message.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger">
            <p><%= msg %></li>
          </div>
        <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control"%>
  </div>
  <div class="form_group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control"%>
  </div>
  <%= f.submit 'Submit', class: "btn btn-default" %>
<% end %>

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
  <% if @page.errors.any? %>
    <h2><%= pluralize(@page.errors.count, "error") %> prohibited this post from being saved!</h2>
    <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="forminputs">
    <div class="form-group">
      <p><%= f.label :title %></p>
      <p><%= f.text_field :title, class: "form-control" %></p>
    </div>

    <div class="form-group">
      <p><%= f.label :content %></p>
      <p><%= f.text_area :content, class: "form-control" %></p>
    </div>

    <%= f.submit 'Submit', :class => "btn btn-primary" %>
  </div>


<% end %>

app/views/pages/edit.html.erb
<h2 class="text-center"><strong>Editing Page</strong></h2>
<%= render 'form' %>
<%= link_to 'Back', posts_path, class: "btn btn-primary pull-right" %>

app/views/pages/index.html.erb
<h2 class="text-center pagetitle"><strong><%= @about_page.title %></strong></h2>
<div class="panel panel-default">
  <div class="panel-body">
    <p><%= markdown @about_page.content %></p>
    <% if user_signed_in? && admin? %>
    <div class="pull-right">
       <%= link_to 'Edit', edit_page_path(@about_page), class: "btn btn-default" %>
    </div>
  <% end %>
  </div>
</div>

app/views/posts/_admin.html.erb
<% if user_signed_in? %>
  <div class="pull-right">
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?'} %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved!</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="forminputs">
    <div class="form-group">
      <p><%= f.label :title %></p>
      <p><%= f.text_field :title, class: "form-control" %></p>
    </div>

    <div class="form-group">
      <p><%= f.label :summary %></p>
      <p><%= f.text_area :summary, class: "form-control" %></p>
    </div>

    <div class="form-group">
      <p><%= f.label :text %></p>
      <p><%= f.text_area :text, class: "form-control" %></p>
    </div>

    <div class="checkbox">
      <%= f.label :is_event, "Is this an event?" %>
      <%= f.check_box :is_event %>
    </div>

    <div class="form-group">
      <p><%= f.label :event_date, "Event date:" %></p>
      <p><%= f.date_select :event_date %></p>
    </div>

    <%= f.submit 'Submit', :class => "btn btn-primary" %>
  </div>


<% end %>

app/views/posts/edit.html.erb
<h2 class="text-center"><strong>Editing Post</strong></h2>
<%= render 'form' %>
<%= link_to 'Back', posts_path, class: "btn btn-primary pull-right" %>

app/views/posts/event_list.html.erb
<h2 class="text-center pagetitle"><strong>Events</strong></h2>
<% @events.each do |post| %>
<div class="panel panel-default">
  <div class="newsTitle panel-heading">
    <h3 class="pull-left">
      <strong><%= post.title %></strong>
    </h3>
     <span class="pull-right"><strong>Event Date:</strong> <%= post.event_date.strftime("%d %b. %Y") %></span>
  </div>
  <div class="panel-body">
    <!--<p><%= raw RedCloth.new(post.text).to_html %></p> -->
    <p><%= markdown post.summary %></p>
    <%= link_to 'Read More', post, class: "btn btn-default" %>
    <% if user_signed_in? %>
    <div class="pull-right">
       <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
      <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-default" %>
    </div>
  <% end %>
  </div>
</div>
<% end %>

<%= will_paginate @events, renderer: BootstrapPagination::Rails%>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="jumbotron">
      <h1><%= link_to "About Us", about_path %></h1>
      <p>WCCC Gaming is a student organization that was founded in spring 2013 as a way to organize casual and gamers on campus as well as in our community. The organization is open to any current WCCC student, and most events are open to the public.</p>
      <p class="signupbtn"><%= link_to 'Sign Up', new_message_path, class: "btn btn-primary btn-lg" %></p>
  </div>
    </div>
</div>
<div class="row">
  <div class="col-xs-8 posts">
    <%= render 'posts' %>
    <div class="text-center">
      <%= will_paginate @pagi, renderer: BootstrapPagination::Rails%>
    </div>

  </div>
  <div class="col-xs-4 events">
      <%= render 'events' %>
  </div>
</div>

app/views/posts/new.html.erb
<h2 class="text-center"><strong>New Post</strong></h2>
<%= render 'form' %>

app/views/posts/news_list.html.erb
<h2 class="text-center pagetitle"><strong>News</strong></h2>
<% @posts.each do |post| %>
<div class="panel panel-default">
  <div class="newsTitle panel-heading">
    <h3 class="pull-left">
      <strong><%= post.title %></strong>
    </h3>
     <span class="pull-right"><%= post.created_at.strftime("%d %b. %Y") %></span>
  </div>
  <div class="panel-body">
    <!--<p><%= raw RedCloth.new(post.text).to_html %></p> -->
    <p><%= markdown post.summary %></p>
    <%= link_to 'Read More', post, class: "btn btn-default" %>
    <% if user_signed_in? %>
    <div class="pull-right">
       <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
      <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-default" %>
    </div>
  <% end %>
  </div>
</div>
<% end %>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails%>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="newsTitle panel-heading">
    <h3 class="pull-left">
      <strong><%= @post.title %></strong>
    </h3>
     <span class="pull-right"><%= @post.created_at.strftime("%d %b. %Y") %></span>
  </div>
  <div class="panel-body">
    <p><%= raw RedCloth.new(@post.text).to_html %></p>
    <div class="pull-right">
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-default' %>
        <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-default' %>
      <% end %>
    </div>
    <%= link_to 'Back', posts_path, class: "btn btn-default" %>
  </div>
</div>